[package]
name = "snake_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
cli-table = "0.4.7"
colored = "3.0.0"
wasmer = "6.0.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.141"}
